spring:
  datasource:
    url: jdbc:postgresql://ec2-43-200-6-157.ap-northeast-2.compute.amazonaws.com:5432/where42
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
