spring:
  datasource:
    url: jdbc:postgresql://ec2-43-200-6-157.ap-northeast-2.compute.amazonaws.com:5432/where42
#    url: jdbc:postgresql://localhost:5432/where42
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
# 오픈소스 전환 시 이 부분 꼭꼭 삭제!!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

logging:
#  file:
#    path: /
  #    path: /home/ec2-user/log
  #    path: /Users/kimseonghun/Desktop/
  level:
    org.hibernate.SQL: debug
